name: CI for ausbotics

on:
  push:
    branches:
      - main
  pull_request:
    types:
      - labeled

jobs:
  build-frontend:
    name: Build Frontend
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./ausbotics-frontend
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: "npm"
          cache-dependency-path: ./ausbotics-frontend/package-lock.json

      - name: Install dependencies
        run: npm ci

      - name: Build Next.js app
        run: npm run build

  build-backend:
    name: Build Backend
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./ausbotics-backend
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: "npm"
          cache-dependency-path: ./ausbotics-backend/package-lock.json

      - name: Install dependencies
        run: npm ci

      - name: Build TypeScript backend
        run: npm run build

      - name: Check Prisma schema
        run: npx prisma validate
